spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=oracle
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081